cli/test: add capabilities flag to test command (#5152)
In order to test rego files that contains custom built-in functions,
users need to generate a custom OPA binary with their custom functions
registered in the capabilities file; otherwise the CLI will throw:

    rego_type_error: undefined function custom.functionName

With this change, we allow users to test rego files with custom built-in
functions by providing a custom capabilities file in the test command.

This is in line with `opa check` and `opa build`.

Signed-off-by: Iván Peña Hernández <ivanphdz13@gmail.com>