internal/wasm: Fix panic caused by invalid heap settings
The wasmtime runtime puts a 4GB limit on the heap which makes sense
given 32-bit addressing.

thread '<unnamed>' panicked at 'assertion failed:
plan.memory.maximum.is_none() ||
    plan.memory.maximum.unwrap() <= WASM_MAX_PAGES', crates/runtime/src/memory.rs:74:9

Signed-off-by: Torin Sandall <torinsandall@gmail.com>